# Generated by Django 6.1 on 2026-08-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='triggered_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
